import fs from "node:fs";
import { join } from "node:path";
import { S3Client, ListObjectsV2Command } from "@aws-sdk/client-s3";

// Public CDN base URL for the Cloudflare R2 bucket.
// Set NEXT_PUBLIC_R2_URL in .env.local (and in production env vars).
const R2_BASE_URL = process.env.NEXT_PUBLIC_R2_URL ?? "";

function getR2Client() {
  const accountId = process.env.R2_ACCOUNT_ID;
  const accessKeyId = process.env.R2_ACCESS_KEY_ID;
  const secretAccessKey = process.env.R2_SECRET_ACCESS_KEY;

  if (!accountId || !accessKeyId || !secretAccessKey) return null;

  return new S3Client({
    region: "auto",
    endpoint: `https://${accountId}.r2.cloudflarestorage.com`,
    credentials: { accessKeyId, secretAccessKey },
  });
}

interface R2Video {
  name: string;
  path: string;
  category: string;
  poster?: string;
}

// Posters are pre-generated by scripts/optimize-videos.mjs and stored next
// to the videos as `<base>-poster.webp`. Serving them as plain images means
// the picker never has to download video bytes to render a swatch.
async function listR2Videos(): Promise<R2Video[]> {
  const client = getR2Client();
  const bucket = process.env.R2_BUCKET_NAME ?? "ambient-assets";

  // R2 is the single source of truth for videos — no local fallback.
  // Without credentials or the public base URL, any returned path would 404
  // anyway, so fail loudly in the server log and serve none.
  if (!client || !R2_BASE_URL) {
    console.warn(
      "[assets] R2 is not fully configured (need R2_ACCOUNT_ID / R2_ACCESS_KEY_ID / " +
      "R2_SECRET_ACCESS_KEY + NEXT_PUBLIC_R2_URL) — serving no videos"
    );
    return [];
  }

  const command = new ListObjectsV2Command({
    Bucket: bucket,
    Prefix: "bg-videos/",
  });

  const response = await client.send(command);
  const keys = new Set((response.Contents ?? []).map(obj => obj.Key!));

  return [...keys]
    .filter(key => /\.(mp4|mov|webm)$/i.test(key))
    .map(key => {
      const name = key.split("/").pop()!;
      const posterKey = `bg-videos/${name.replace(/\.[^.]+$/, "")}-poster.webp`;
      return {
        name,
        path: `${R2_BASE_URL}/${key}`,
        category: "bg-videos",
        poster: keys.has(posterKey) ? `${R2_BASE_URL}/${posterKey}` : undefined,
      };
    })
    .sort((a, b) => {
      // Sort numerically by filename (1.mp4, 2.mp4 … 10.mp4, not lexicographic)
      const numA = parseInt(a.name, 10);
      const numB = parseInt(b.name, 10);
      if (!isNaN(numA) && !isNaN(numB)) return numA - numB;
      return a.name.localeCompare(b.name);
    });
}

export async function GET() {
  const papersDir = join(process.cwd(), "public", "papers");
  const modernDir = join(process.cwd(), "public", "modern-backgrounds");
  const doodlesDir = join(process.cwd(), "public", "doodles");

  try {
    const listDir = (dir: string, prefix: string, extensions = /\.(jpg|jpeg|png|webp|svg)$/i) => {
      if (!fs.existsSync(dir)) return [];
      return fs.readdirSync(dir)
        .filter(f => f.match(extensions))
        .map(name => ({
          name,
          path: `/${prefix}/${name}`,
          category: prefix,
        }));
    };

    const papers = listDir(papersDir, "papers");
    const modern = listDir(modernDir, "modern-backgrounds");
    const videos = await listR2Videos();
    const doodles = listDir(doodlesDir, "doodles").map(d => d.name);

    return Response.json({
      papers: [...papers, ...modern],
      videos,
      doodles,
    }, {
      headers: {
        // Cache for 5 min in browser, 10 min at CDN — videos/doodles rarely change
        "Cache-Control": "public, max-age=300, s-maxage=600, stale-while-revalidate=3600",
      },
    });
  } catch (error) {
    return Response.json({ papers: [], videos: [], doodles: [] });
  }
}

